module.exports = {
    "/":{
        "get":"index.index"
    },
    "/bouboup":{
        "get":"index.bouboup"
    },
    "/back/{$module}":{
        "parameters":{
            "module":"[a-zA-Z-_]+"
        },
        "*":"back/{$module}.index"
    },
    "/back/{$module}/{$method}":{
        "parameters":{
            "module":"[a-zA-Z-_]+",
            "method":"[a-zA-Z_]+"
        },
        "*":"back/{$module}.{$method}"
    }
};